version: "3.9"

services:
  digital-plant-sql-db:
    image: postgres:15.3-alpine
    container_name: microservices-sql-db
    environment:
      POSTGRES_DB: "microservices"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -D microservices" ]
      interval: 5s
      timeout: 2s
      retries: 25
    ports:
      - "5433:5432"
    volumes:
      - db_microservices_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "max-connections=400" ]

volumes:
  db_microservices_data: {}