spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/microservices?currentSchema=company-schema'
    username: user
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: company-service-group
      topic:
        company-deleted-user: company-deleted-user-topic
    producer:
      group-id: company-service-group
      topic:
        company-deleted: company-deleted-topic


  liquibase:
    enabled: true
    change-log: classpath:db/migration.sql

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

test: default
my:
  property:
    test: company-service

description: "hi i am company-service"
