spring:
  datasource:
    url: 'jdbc:postgresql://host.docker.internal:5433/microservices?currentSchema=user-schema'
    username: user
    password: password

server:
  port: 8089

test: default
my:
  property:
    test: user-service

description: "hi i am user-service"

