spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/microservices?currentSchema=user-schema'
    username: user
    password: password


  liquibase:
    enabled: false
    change-log: classpath:db/migration.sql

server:
  port: 8089

test: default
my:
  property:
    test: user-service

description: "hi i am user-service"

