spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/microservices?currentSchema=user-schema'
    username: user
    password: password


  liquibase:
    enabled: true
    change-log: classpath:db/migration.sql

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

test: default
my:
  property:
    test: user-service

description: "hi i am user-service"

