spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/microservices?currentSchema=user-schema'
    username: user
    password: password
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-service-group
      topic:
        company-deleted: company-deleted-topic
    producer:
      bootstrap-servers: localhost:9092
      group-id: user-service-group
      topic:
        company-deleted-user: company-deleted-user-topic


  liquibase:
    enabled: true
    change-log: classpath:db/migration.sql

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

test: default
my:
  property:
    test: user-service

description: "hi i am user-service"

