-- liquibase formatted sql

-- changeset reinner:1702831006006-1
CREATE SEQUENCE  IF NOT EXISTS company_ds_seq START WITH 1 INCREMENT BY 50;

-- changeset reinner:1702831006006-2
CREATE TABLE company_ds (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deleted BOOLEAN NOT NULL, description VARCHAR(255), name VARCHAR(255), ogrn VARCHAR(255), user_id BIGINT, CONSTRAINT "company_dsPK" PRIMARY KEY (id));

